DROP DATABASE IF EXISTS myapp;
CREATE DATABASE myapp;

USE myapp;

CREATE TABLE IF NOT EXISTS `user` (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(40) UNIQUE NOT NULL,
	EMAIL VARCHAR(120) UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL,
	USER_ROLE VARCHAR(20) NOT NULL DEFAULT 'USER'
);

INSERT INTO `user` (USERNAME, EMAIL, PASSWORD, USER_ROLE)
VALUES ('admin', 'admin@example.com', '120000$jNUAnZQ/vdgLGnfLv7L+fw==$vd1yIYl5gFGO/6HdIECR8a8sn2HH6gQENQniPEAntSY=', 'ADMIN')
ON DUPLICATE KEY UPDATE USER_ROLE = 'ADMIN';

CREATE TABLE IF NOT EXISTS feedback (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(40) NOT NULL,
	FEEDBACK TEXT NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_FEEDBACK_USER FOREIGN KEY (USERNAME) REFERENCES `user` (USERNAME) ON DELETE CASCADE
);

SELECT * FROM feedback;

select * from `user`;